newPRWelcomeComment: >
  Thanks so much for opening your first Pull Reuuest here!

newIssueWelcomeComment: >
  Thanks for opening this issue, a maintainer will get back to you shortly!

firstPRMergeComment: >
  Congrats on merging your first pull request here! :tada: How awesome!
